TEMPLATE_BOXES = {
    "POS01": {
        "page_1":
            [{'name': 'field',
              'type': 'text',
              'position': {'top': 1951, 'left': 1173},
              'size': {'width': 1224, 'height': 110}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1607, 'left': 457},
                 'size': {'width': 787, 'height': 119}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1092, 'left': 1621},
                 'size': {'width': 748, 'height': 110}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1620, 'left': 1506},
                 'size': {'width': 358, 'height': 79}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1875, 'left': 1062},
                 'size': {'width': 727, 'height': 84}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1872, 'left': 487},
                 'size': {'width': 387, 'height': 85}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1781, 'left': 665},
                 'size': {'width': 886, 'height': 97}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1625, 'left': 2085},
                 'size': {'width': 301, 'height': 86}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1192, 'left': 608},
                 'size': {'width': 752, 'height': 72}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1345, 'left': 415},
                 'size': {'width': 1922, 'height': 120}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1712, 'left': 501},
                 'size': {'width': 749, 'height': 79}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1546, 'left': 1725},
                 'size': {'width': 703, 'height': 87}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1261, 'left': 1599},
                 'size': {'width': 731, 'height': 88}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1263, 'left': 667},
                 'size': {'width': 735, 'height': 94}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1189, 'left': 1549},
                 'size': {'width': 785, 'height': 79}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1103, 'left': 524},
                 'size': {'width': 835, 'height': 101}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 1006, 'left': 657},
                 'size': {'width': 1820, 'height': 111}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 603, 'left': 876},
                 'size': {'width': 1456, 'height': 114}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 691, 'left': 1041},
                 'size': {'width': 1299, 'height': 110}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 512, 'left': 1567},
                 'size': {'width': 729, 'height': 90}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 504, 'left': 673},
                 'size': {'width': 598, 'height': 105}}],

                 
        "page_2": [{'name': 'field',
                    'type': 'text',
                    'position': {'top': 3055, 'left': 1193},
                    'size': {'width': 649, 'height': 106}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 3055, 'left': 526},
                    'size': {'width': 535, 'height': 95}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 2815, 'left': 360},
                    'size': {'width': 371, 'height': 79}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 2707, 'left': 433},
                    'size': {'width': 805, 'height': 125}}]
    },

    "POS04": {
        "page_1":
            [{'name': 'field',
              'type': 'text',
              'position': {'top': 430, 'left': 583},
              'size': {'width': 958, 'height': 66}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 714, 'left': 844},
                 'size': {'width': 348, 'height': 65}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 492, 'left': 689},
                 'size': {'width': 858, 'height': 67}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 370, 'left': 1037},
                 'size': {'width': 488, 'height': 65}},
                {'name': 'field',
                 'type': 'text',
                 'position': {'top': 368, 'left': 447},
                 'size': {'width': 399, 'height': 63}}],
        "page_2": [{'name': 'field',
                    'type': 'text',
                    'position': {'top': 1639, 'left': 287},
                    'size': {'width': 263, 'height': 62}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1643, 'left': 1368},
                    'size': {'width': 203, 'height': 52}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1556, 'left': 330},
                    'size': {'width': 554, 'height': 95}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1639, 'left': 982},
                    'size': {'width': 251, 'height': 57}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1575, 'left': 1024},
                    'size': {'width': 550, 'height': 69}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1800, 'left': 843},
                    'size': {'width': 493, 'height': 80}},
                   {'name': 'field',
                    'type': 'text',
                    'position': {'top': 1798, 'left': 391},
                    'size': {'width': 363, 'height': 81}}]
    },
}
